-- MySQL Script generated by MySQL Workbench
-- Fri Aug 25 09:03:21 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema brightideas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema brightideas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `brightideas` DEFAULT CHARACTER SET utf8 ;
USE `brightideas` ;

-- -----------------------------------------------------
-- Table `brightideas`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brightideas`.`Users` (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL,
  `Alias` VARCHAR(255) NULL,
  `Email` VARCHAR(255) NULL,
  `Password` VARCHAR(255) NULL,
  `CreatedAt` DATETIME NULL,
  `UpdatedAt` DATETIME NULL,
  PRIMARY KEY (`UserId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brightideas`.`Ideas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brightideas`.`Ideas` (
  `IdeaId` INT NOT NULL AUTO_INCREMENT,
  `CreatedById` INT NULL,
  `IdeaText` TEXT NULL,
  `CreatedAt` DATETIME NULL,
  `UpdatedAt` DATETIME NULL,
  PRIMARY KEY (`IdeaId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brightideas`.`Likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brightideas`.`Likes` (
  `LikeId` INT NOT NULL AUTO_INCREMENT,
  `IdeaId` INT NOT NULL,
  `UserId` INT NOT NULL,
  PRIMARY KEY (`LikeId`, `IdeaId`, `UserId`),
  INDEX `fk_Likes_Ideas_idx` (`IdeaId` ASC),
  INDEX `fk_Likes_Users1_idx` (`UserId` ASC),
  CONSTRAINT `fk_Likes_Ideas`
    FOREIGN KEY (`IdeaId`)
    REFERENCES `brightideas`.`Ideas` (`IdeaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Likes_Users1`
    FOREIGN KEY (`UserId`)
    REFERENCES `brightideas`.`Users` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
