-- MySQL Script generated by MySQL Workbench
-- Wed Aug 23 13:41:20 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema brightideas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema brightideas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `brightideas` DEFAULT CHARACTER SET utf8 ;
USE `brightideas` ;

-- -----------------------------------------------------
-- Table `brightideas`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brightideas`.`Users` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL,
  `Alias` VARCHAR(255) NULL,
  `Email` VARCHAR(255) NULL,
  `Password` VARCHAR(255) NULL,
  `CreatedAt` DATETIME NULL,
  `UpdatedAt` DATETIME NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brightideas`.`Ideas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brightideas`.`Ideas` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `CreatedBy` VARCHAR(255) NULL,
  `Idea` TEXT NULL,
  `CreatedAt` DATETIME NULL,
  `UpdatedAt` DATETIME NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brightideas`.`Likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brightideas`.`Likes` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Idea_Id` INT NOT NULL,
  `User_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `Idea_Id`, `User_Id`),
  INDEX `fk_Likes_Ideas_idx` (`Idea_Id` ASC),
  INDEX `fk_Likes_Users1_idx` (`User_Id` ASC),
  CONSTRAINT `fk_Likes_Ideas`
    FOREIGN KEY (`Idea_Id`)
    REFERENCES `brightideas`.`Ideas` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Likes_Users1`
    FOREIGN KEY (`User_Id`)
    REFERENCES `brightideas`.`Users` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
